// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Groth16Verifier as generated by `snarkjs zkey export solidityverifier`
///         from build/pov_final.zkey (11 public signals, in the order of Eq. (12)).
interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[11] calldata pubSignals
    ) external view returns (bool);
}

/// @notice Adapts the generated Groth16 verifier to the `(bytes, uint256[])`
///         shape TrustAnchor calls.
///
/// The generated contract fixes both the argument arity and the public-signal
/// count at export time, so the flat encoding used by the relay payload is
/// decoded here rather than in TrustAnchor. `proof` is the 8 field elements of
/// (A, B, C) in snarkjs order, abi-encoded; `publicSignals` must carry exactly
/// the 11 signals of the public instance x.
contract PoVVerifierAdapter {
    uint256 internal constant PUBLIC_SIGNALS = 11;

    IGroth16Verifier public immutable groth16;

    constructor(address groth16_) {
        require(groth16_ != address(0), "verifier required");
        groth16 = IGroth16Verifier(groth16_);
    }

    function verifyProof(bytes calldata proof, uint256[] calldata publicSignals)
        external
        view
        returns (bool)
    {
        if (publicSignals.length != PUBLIC_SIGNALS) return false;
        if (proof.length != 32 * 8) return false;

        uint256[8] memory p = abi.decode(proof, (uint256[8]));

        uint256[2] memory pA = [p[0], p[1]];
        uint256[2][2] memory pB = [[p[2], p[3]], [p[4], p[5]]];
        uint256[2] memory pC = [p[6], p[7]];

        uint256[PUBLIC_SIGNALS] memory signals;
        for (uint256 i = 0; i < PUBLIC_SIGNALS; i++) {
            signals[i] = publicSignals[i];
        }

        return groth16.verifyProof(pA, pB, pC, signals);
    }
}
